name: Nx Affected Apps
on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'App Name'
        required: true
        default: 'customers-app'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: git fetch origin master
      - run: npm install
      - run: |
          echo "App Name: ${{ inputs.app-name }}"
      - name: Build App
        shell: bash
        run: npm run build ${{ inputs.app-name }}
      - name: Test App
        shell: bash
        run: npm run test ${{ inputs.app-name }}
      - name: Build App
        shell: bash
        run: npm run build ${{ inputs.app-name }}
      - name: Containerize App
        shell: bash
        run: |
           echo "TBD"
      - name: Deploy App
        shell: bash
        run: |
           echo "TBD"
